# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark and close stale issues

on:
  schedule:
  - cron: '30 1 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.STALE_TOKEN }}
        days-before-stale: 90
        ignore-pr-updates: true
        days-before-pr-stale: -1
        days-before-pr-close: -1
        stale-issue-message: 'This issue is stale because it has been open 180 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
        stale-issue-label: 'stale'
        exempt-issue-labels: 'bug, enhancement'
        exempt-all-assignees: true
